name: Continuous Deployment - Backend

on:
  push:
    branches: [feature/87-cicd]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.TEST_REGION }}
          aws-access-key-id: ${{ secrets.TEST_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.TEST_SECRET_ACCESS_ID }}
          instance-ids: ${{ secrets.TEST_INSTANCE_ID }}

          working-directory: /home/ec2-user
          command: sh deploy.sh